In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
type(l)

list

In [5]:
np.array(l)

array([1, 2, 3, 4])

In [6]:
a = np.array(l)

In [7]:
a

array([1, 2, 3, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a1 = np.array([[1,2,3], [4,5,6]])

In [10]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a1.dtype

dtype('int32')

In [12]:
type(a1)

numpy.ndarray

In [13]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [14]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [15]:
a.ndim #Direction 1d

1

In [16]:
a1.ndim #2d

2

In [17]:
a2.ndim #3d

3

In [18]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
a3.ndim

3

In [21]:
l = [1,2,3,4]

In [22]:
np.asanyarray(l) #1d data only

array([1, 2, 3, 4])

In [23]:
m = np.matrix(l) #2d dataset 

In [24]:
m

matrix([[1, 2, 3, 4]])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
m

matrix([[1, 2, 3, 4]])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
a[0]

1

In [29]:
a[0] = 10

In [30]:
a

array([10,  2,  3,  4])

In [31]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a1[1]

array([4, 5, 6])

In [34]:
a1[0]

array([1, 2, 3])

In [35]:
a1[0][1]

2

In [36]:
a1[0][1] = 40

In [37]:
a1

array([[ 1, 40,  3],
       [ 4,  5,  6]])

In [38]:
np.random.rand(2,3) #2 rows and 3columns

array([[0.48115037, 0.91383065, 0.15813221],
       [0.55994314, 0.9611144 , 0.54836515]])

In [39]:
np.random.rand(2,3,2)

array([[[0.40698692, 0.43578031],
        [0.97479892, 0.00933665],
        [0.5682969 , 0.14695957]],

       [[0.00425924, 0.08173504],
        [0.45148098, 0.23423719],
        [0.55297632, 0.48359715]]])

In [40]:
np.random.rand(2,3,2,2)

array([[[[0.14849311, 0.79829186],
         [0.27744377, 0.29712236]],

        [[0.95640028, 0.59048977],
         [0.72630395, 0.73168482]],

        [[0.47802781, 0.96628823],
         [0.19008672, 0.39415696]]],


       [[[0.92037805, 0.84466707],
         [0.56882805, 0.94397051]],

        [[0.27856271, 0.19826694],
         [0.33846241, 0.69423725]],

        [[0.30706145, 0.47085008],
         [0.52064209, 0.28541789]]]])

In [41]:
np.random.rand(1,4,4)

array([[[0.41584037, 0.99192132, 0.32145492, 0.18512365],
        [0.59480548, 0.51030025, 0.08006517, 0.56254506],
        [0.80218581, 0.10008574, 0.13185264, 0.8519692 ],
        [0.29111288, 0.88524777, 0.32610468, 0.1112419 ]]])

In [43]:
np.random.rand(4,4,4)

array([[[0.34166662, 0.1647296 , 0.34206056, 0.58751939],
        [0.67353776, 0.53990602, 0.38814901, 0.06287842],
        [0.14982784, 0.7783435 , 0.42764113, 0.98725788],
        [0.12663651, 0.21507312, 0.24925787, 0.8322203 ]],

       [[0.44001164, 0.52503306, 0.84817509, 0.01957458],
        [0.27124238, 0.47166355, 0.48216365, 0.79117239],
        [0.69873551, 0.81560433, 0.31135045, 0.61299172],
        [0.0631368 , 0.25423811, 0.97535933, 0.19713013]],

       [[0.51175028, 0.44744105, 0.0342157 , 0.00721438],
        [0.88151919, 0.28953892, 0.57806041, 0.42069168],
        [0.85286059, 0.09784773, 0.10851331, 0.00420055],
        [0.79789742, 0.68556032, 0.62250735, 0.01168694]],

       [[0.5094388 , 0.06238139, 0.18906677, 0.41989093],
        [0.21785914, 0.2019434 , 0.21213828, 0.12841536],
        [0.33097163, 0.83354952, 0.55016883, 0.95716207],
        [0.41354001, 0.78695118, 0.08568751, 0.21998743]]])

In [44]:
np.random.randint(0,10,(4,4))

array([[4, 7, 1, 6],
       [4, 0, 3, 3],
       [1, 4, 6, 6],
       [5, 7, 6, 0]])

In [45]:
np.random.randint(30,50,(2,4))

array([[47, 44, 31, 47],
       [49, 39, 46, 36]])

In [46]:
np.random.randint(30,50,(1,10))

array([[37, 36, 41, 35, 38, 49, 45, 34, 36, 37]])